In [179]:
data = readlines("data_9.txt")
#data = readlines("expample.txt")

2000-element Vector{String}:
 "U 1"
 "R 1"
 "L 1"
 "D 1"
 "R 1"
 "L 1"
 "D 1"
 "L 2"
 "D 1"
 "R 1"
 "D 2"
 "L 1"
 "R 1"
 ⋮
 "U 10"
 "L 14"
 "R 15"
 "D 19"
 "L 13"
 "U 4"
 "L 8"
 "U 8"
 "L 7"
 "D 5"
 "R 17"
 "U 8"

In [143]:
function tail_around(head,tail)
    if head[1] -1 <= tail[1] <= head[1] + 1
        if head[2] - 1 <= tail[2] <= head[2] + 1
            return true
        end
    end
    return false
end

tail_around (generic function with 1 method)

In [105]:
#first
head = [1,1] #y,x
tail = [1,1]
index = 0
head_pre = [0,0]
tail_moves = []
grid = zeros(Int8, 6, 6)
for line in data
    move = split(line, " ")
    move_now = [0,0]
    for moves in 1:parse(Int,move[2])
        # if grid[head[1], head[2]] != 2
        #     grid[head[1], head[2]] = 0
        # end
        if move[1] == "R"
            move_now[2] = 1
        elseif move[1] == "L"
            move_now[2] = -1
        elseif move[1] == "U"
            move_now[1] = 1
        elseif move[1] == "D"
            move_now[1] = -1
        end
        head_pre = head
        head += move_now
        tail_is_around = tail_around(head, tail)
        if !tail_is_around
            tail = head_pre
        end
        # if grid[head[1], head[2]] != 2
        #     grid[head[1], head[2]] = 1
        # end
        if !any(i -> (i == tail), tail_moves)
            push!(tail_moves, tail)
        end
        # grid[tail[1], tail[2]] = 2
        # grid[tail] = 0
        move_pre = move_now
        # println(tail_is_around)
        # println(head, " ", tail)
        # display(grid)
    end
end
# count(i->(i==2), grid)
# tail_moves
length(tail_moves)

6503

In [142]:
function move_tail(head,tail)
    if head[1] == tail[1]
        if head[2] > tail[2]
            return [0,1]
        else
            return [0,-1]
        end
    elseif head[2] == tail[2]
        if head[1] > tail[1]
            return [1,0]
        else
            return [-1,0]
        end
    elseif head[1] > tail[1]
        if head[2] > tail[2]
            return [1,1]
        else
            return [1,-1]
        end
    elseif head[1] < tail[1]
        if head[2] > tail[2]
            return [-1,1]
        else
            return [-1,-1]
        end
    end
end
        

move_tail (generic function with 1 method)

In [182]:
#second
head = [16,12] #y,x
start = [16,12]
tails = fill([0,0], 9)
index = 0
tail_moves = []
grid = zeros(Int8, 27, 27)
for line in data
    move = split(line, " ")
    move_now = [0,0]
    for moves in 1:parse(Int,move[2])

        if move[1] == "R"
            move_now[2] = 1
        elseif move[1] == "L"
            move_now[2] = -1
        elseif move[1] == "U"
            move_now[1] = 1
        elseif move[1] == "D"
            move_now[1] = -1
        end
        head += move_now
        for tail_i in 1:length(tails)
            if tails[tail_i] == [0,0]
                tails[tail_i] = start
            end
            if tail_i == 1
                tail_is_around = tail_around(head, tails[tail_i])
                if !tail_is_around
                    tails[tail_i] += move_tail(head,tails[tail_i])
                end
            else
                tail_is_around = tail_around(tails[tail_i-1], tails[tail_i])
                if !tail_is_around
                    tails[tail_i] += move_tail(tails[tail_i-1], tails[tail_i])
                end
            end
            if tail_i == 9 && !any(i -> (i == tails[tail_i]), tail_moves)
                push!(tail_moves, tails[tail_i ])
            end
            if tails[tail_i] == start
                break
            end
        end
    end
end
length(tail_moves)

2724

In [177]:
length(tail_moves)

33

In [82]:
[grid2; zeros(Int8,6)']

7×6 Matrix{Int8}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [94]:
setti = [(1,2), (2,3), (5,4)]

3-element Vector{Tuple{Int64, Int64}}:
 (1, 2)
 (2, 3)
 (5, 4)

In [97]:
if any(i -> (i == (1,2)), setti)
    println("juu")
end

juu


In [122]:
fill([0,0], 10)

10-element Vector{Vector{Int64}}:
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]
 [0, 0]